### ISSUE TITLE
Attach backend to app instance

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-taxii-server#1]
Rather than calling `get_backend()` all the time, we can just create it when the app loads and attach it to the `Flask` object: https://github.com/oasis-open/cti-taxii-server/blob/master/medallion/__init__.py#L6

We don't need to worry about lazily instantiating the variable. If it isn't valid, we can error out quickly when the server is starting.

**Comment by gtback** [comment]
@rpiazza said he tried to do something like this at one point and ran into problems, so it may be more difficult than I'd hoped. More investigation may be needed.

**Comment by rpiazza** [comment]
This is what I looked in http://flask.pocoo.org/docs/0.12/appcontext/
I don't remember if I determined it is impossible or I just gave up.

I think this only allows globals on the per request basis.
