### ISSUE TITLE
Issue while running docker on Mac

### ISSUE THREAD

**Issue by kp625544** [oasis-open/cti-taxii-server#103]
Following issue occurred while installing cti-taxii-server via docker on Mac
Step 3/5 : COPY ./docker_utils/*.json /opt/taxii
COPY failed: no source files were specified

**Comment by zrush-mitre** [comment]
Hi @kp625544,

Assuming you have not moved the Dockerfile from the docker_utils folder, you have to call `docker build` with a path specification like so: `docker build . -f docker_utils/Dockerfile -t medallion`. 

Were you following the instructions in the readme? I noticed that we don't specify where the Dockerfile is, so I will make a PR to add some description and link to this issue.

Hope this helps.

**Comment by kp625544** [comment]
Fixed the issue will send a merge request for the same.

**Comment by emmanvg** [comment]
closed by #104
