### ISSUE TITLE
404 error for /discovery

### ISSUE THREAD

**Issue by batuhankutluca** [oasis-open/cti-taxii-server#122]
I'm trying to get api roots by making get request via cti-taxii-client for http://ip:port/discovery but it gives http 404 error. I'm using your config.json and default_data.json files for testing without any changes. So the thing is when I do the same request to http://ip:port/trustgroup1 and print the server.title, it prints "Malware Research Group" as usual. But I want to get api roots by querying /discovery, so I can move on with selecting the correct collection and correct object. Here is my code:

from taxii2client.v21 import Server
server = Server('http://localhost:80/trustgroup1/', user='admin', password='Password0')
print(server.title)			

As I said, it gives output. But that's not the thing I need. I need to select api_root by querying /discovery url. So I can get my Threat Intelligence data inside collections.

I couldn't find my mistake. Please help me. Thanks in advance.

**Comment by zrush-mitre** [comment]
Hi @batuhankutluca,

While the the section of the data may be under `/discovery`, you actually access the endpoint by using `http://ip:port/taxii2`, as referenced in the readme for the taxii-client [here](https://github.com/oasis-open/cti-taxii-client). The endpoint specification can also be seen in section 3.1 of the TAXII spec [here](https://docs.oasis-open.org/cti/taxii/v2.1/cs01/taxii-v2.1-cs01.pdf). 

Hopefully this solves your problem and if you have any others, feel free to post more in here.

Thanks!

**Comment by batuhankutluca** [comment]
Hi @zrush-mitre ,

Thank you for your reply. Now I can access objects, api roots etc. by requesting /taxii2 directory. For some reason when I see the top root in data.json as /discovery, I thought I have to access with requesting /discovery. But still I don't understand where it is defined. I mean how does my server know when taxii client wants to get data by requesting /taxii directory it actually requesting "/discovery" section in my data.json file? Sorry If my question is too dumb, I would be appreciated if you can tell.

**Comment by zrush-mitre** [comment]
Hi @batuhankutluca,

No question is too dumb! Lots of questions and information can be needed to really understand what is happening.

Depending upon what backend you're using will change how the data is actually retrieved, but all the default backends on the server will go through the functions defined in the views directory. For the discovery endpoint, we use the flask-defined `Blueprint` object, which allows backends to be modular. This object allows us to route a URL to a specific function which then starts the data collection. For the discovery endpoint, if you look in the `discovery.py` file, you can see that the path /taxii2 is routed to the `get_server_discovery` function, which will then call the defined backend's function to return metadata about the server. If you wanted to, you could change the discovery route to be '/discovery', and get the data about the server back with that path instead.

I hope with that information, you can follow the functions as they go through the files to eventually get the data created in the files in the backend. 

Let me know if I can help or give some more info in anyway to help out.

Thanks.

**Comment by batuhankutluca** [comment]
Hi @zrush-mitre 

Thanks for your explanation again. No issue left that I was facing from now. I'm closing the issue. 

Thank you and your team with this powerful repository. Have a great day !
