### ISSUE TITLE
Adding STIX indicators to the database

### ISSUE THREAD

**Issue by c52-k** [oasis-open/cti-taxii-server#123]
Hi, 
According to the STIX specifications, if the same indicator is viewed more than once, the sighting count for that indicator should increase. Is it something that is implemented in the taxii server level? Or is it something that has to be checked manually before sending the indicator to the taxii server (and modify the corresponding sighting object instead of sending the indicator)?

I am new to STIX/TAXII and would appreciate it very much if someone can clarify this. 
Thanks!

**Comment by emmanvg** [comment]
Hi @c52-k, issuing an update to a STIX object can only be performed by the object creator (the entity/organization who created the object) hence it is out of scope for TAXII purposes. Therefore, the producer is the one in charge of versioning the sighting object and update the count, then sending the updated sighting object to the server.

References:
Section 3.5 & 3.6 STIX 2.1: https://docs.oasis-open.org/cti/stix/v2.1/cs01/stix-v2.1-cs01.html#_gckz8qcky97t

**Comment by c52-k** [comment]
Thanks for the clarification!
