### ISSUE TITLE
Should a duplicate object trigger a failure status-details

### ISSUE THREAD

**Issue by saaj** [oasis-open/cti-taxii-server#131]
Medallion running on the MongoDB backend, when requested to add duplicate objects into a collection treats them as failures, which is represented in the returned status resource's `status-details` structures. They look like this and are created [here][2]:

```
{
    "id": "identity--f8aab11f-9085-4baa-b06c-4b11a0ef80ee",
    "message": "Unable to process object because an identical entry already exists in collection '62a0ae...'.",
    "version": "2000-01-01T00:00:00Z"
}
```

TAXII 2.1 spec in [5.5 Add Objects][1] says:

> If a client publishes an exact duplicate of an Object already present in the Collection, the server **MUST** not return an error for that Object.

It's not fully clear what the spec means by "an error for that Object". There's the error message type, defined in [3.6.1 Error Message][3]. But it's per request, not per object. Per object error in the context of request to `POST /{api-root}/collections/{id}/objects/` can only be a `status-details`.

If the above interpretation is correct, then it's a bug in Medallion.

[1]: https://docs.oasis-open.org/cti/taxii/v2.1/cs01/taxii-v2.1-cs01.html#_4miz6vh6cpf5
[2]: https://github.com/oasis-open/cti-taxii-server/blob/95bad2f9b90ab0d2c3797a4b706847e3cd243aca/medallion/backends/mongodb_backend.py#L262
[3]: https://docs.oasis-open.org/cti/taxii/v2.1/cs01/taxii-v2.1-cs01.html#_Toc31107521

**Comment by zrush-mitre** [comment]
Hi @saaj,

We currently do not treat a failure status as an error, so the way the server responds to duplicate objects is not in violation of the spec. While the language is slightly confusing, if anything this is a problem with the specification language, and not the medallion server.

Let me know if I need to clarify my answer any more, or if you have other questions.

Thanks.

**Comment by saaj** [comment]
Thanks for clarification @zrush-mitre. Closing this issue as your answer sufficiently covers Medallion's interpretation.
