### ISSUE TITLE
Recommendations for production?

### ISSUE THREAD

**Issue by maybe-sybr** [oasis-open/cti-taxii-server#132]
I've been making use of medallion for a while, with the nagging concern that eventually I'd have to face up to the "not intended for production" bit in the README. As far as I can tell, there's no viable FOSS alternative to medallion in the TAXII 2 ecosystem.

* MITRE has a TAXII 2.0 implementation which is deployed at [0] and allegedly node.js based [1], but I can't find much mention of it except for the article at [1]. Since the primary maintainers here are from MITRE, I'd guess it's not relevant any more?
* Eclectiq have OpenTAXII which hasn't implemented TAXII 2.0 or 2.1 [2], and there doesn't seem to be much focus on making that happen
* S-TIP has simply wrapped OpenTAXII [3]
* Stephen Russett's TAXIIServer [4] appears to have no pulse since February and has some notable problematic stubs [5]
* ubertaxii disappeared in 2019 and the code was never linked on the CTI mailing list AFAICT [6]
* FreeTAXII [7] hasn't has a pulse since late 2018

This is just a long winded way of me asking what we might be able to do if I wanted to continue using medallion in an environment that isn't a toy. Specifically, I'm working toward a long term, HA deployment for hundreds of thousands to millions of STIX documents with extra dynamicism such as the ability to , an auth backend, &c. I think this would be achievable in medallion with some work on the backend implementations, the configuration mechanism and how it runs.

**Is there appetite from the maintainers to help me make this happen?** If so, it'd be nice to discuss what you all think might be in or out of scope, what should live in medallion itself and what should be punted out to some external deployment repository.

===== 8< =====
[0] https://cti-taxii.mitre.org/
[1] https://www.mitre.org/capabilities/cybersecurity/overview/cybersecurity-blog/attck%E2%84%A2-content-available-in-stix%E2%84%A2-20-via
[2] https://github.com/eclecticiq/OpenTAXII/issues/167
[3] https://github.com/s-tip/stip-txs
[4] https://github.com/StephenOTT/TAXII-Server
[5] https://github.com/StephenOTT/TAXII-Server/blob/master/src/main/kotlin/com/github/stephenott/stix/taxii/security/SecurityProvider.kt#L15
[6] https://markmail.org/search/?q=ubertaxii+list%3Aorg.oasis-open.lists.cti+order%3Adate-backward
[7] https://github.com/freetaxii/server

**Comment by zrush-mitre** [comment]
Hi @maybe-sybr,
 
Our team had a discussion this morning, and we will more than welcome any PRs for improvements or new features for the TAXII server, though how it will get merged into the code will depend upon what is being implemented, how effective the code is, and how confident we are in our maintenance capabilities of it. We are more than willing to work with you to answer questions, or help with implementation of something, but currently, adding and improving features for the server are not a priority of ours; we are focusing mainly on bug fixes and specification changes as needed. 
 
We don’t know exactly what you want to implement into a TAXII server, so what would be and what would not be in scope would depend upon the feature or ability being added. We are happy to help give advice for something specific if you’d like. I know you mentioned authentication, and that is something we have talked about working on in the past, but remember that we have two server backends ported over to 2.1 to think about, as well as the legacy 2.0 code on a separate branch (this has some extra authentication features that were not ported over, so keep that in mind).
 
All-in-all, we encourage you to work on and (if you want) submit code to be pulled into the main repo. If you have any more questions, or want a more in-depth chat with the team about this or other topics, feel free to reply here, make another issue, or contact one of the team directly.
 
Thanks.

**Comment by maybe-sybr** [comment]
Thanks for the reply, @zrush-mitre. I'll start making some more specific issues to thread out some of those conversations as I have time this coming week. I think the most interesting discussion would be around control-plane features like collection management since they're not captured in the TAXII spec and I'd understand reluctance to add maintenance burden for things like that. For now, I'll close this since I don't think there's anything to follow up on at this high level.

**Comment by thamamo** [comment]
Hello Dear @zrush-mitre,

Like Mr./Ms. @maybe-sybr , I would like to use the medallion, 
but please tell me the meaning of the following sentence in the Readme.

**"WARNING: medallion was designed as a prototype and reference implementation of TAXII 2.1, and is not intended for production use."**

Medallion is not configured to be publicly available for production by default,
If I want to go public in production, I have to make the necessary changes myself, right?

For example, create an interface with Gunicorn. 
(Because SSL communication is required.)

This is a rudimentary question, but please forgive me because I am a beginner.

Best regards,
thamamo

**Comment by zrush-mitre** [comment]
Hi @thamamo,

You have that right. There are a lot of things missing from the taxii server implementation on here, including, but not limited to, the lack of effective authentication protocols, no standing encryption on passwords or data, and relatively inefficient execution.

You should have a pretty good understanding of web servers and web interface programming before making a TAXII server publicly available, as to avoid issues of compliance, security, and efficiency, but these are all things that you can learn while you are implementing your own server.

Feel free to use the medallion server as you see fit, but it is highly advised not to use it for production.

Let me know if you have any other questions, and feel free to make new issues if you come across any.

Thanks,
Zach

**Comment by rpiazza** [comment]
@thamamo,

Continuing on from what Zach said - medallion is a "reference implementation" - an _example_ of how to implement a TAXII server.  If you use medallion as the basis of your implementation, remember we are happy to consider contributions via a pull request.  See the README for details.

**Comment by thamamo** [comment]
Hi @zrush-mitre, @rpiazza,

Thank you for answering so quickly.
What I wanted to ask became clear.

Before considering whether to use it in production, 
I would like to learn more about the medallion.

Thanks and regards,
thamamo
