### ISSUE TITLE
[RFC] Rework medallion configuration

### ISSUE THREAD

**Issue by maybe-sybr** [oasis-open/cti-taxii-server#135]
At the moment we pass a config file path to `medallion.load_app()` which is a bit of a pain and makes it a bit annoying to use a WSGI server. It would also be nice to move away from having a single config file to supporting something more like a conf.d structure with multiple JSON documents, as well as sourcing some configuration from the environment (e.g. 12 factor app style secrets).

I've been looking into `environ-config` [0] which looks reasonable but might make the arbitrary kwarg passing currently done for backends painful. I've also been looking at `jsonmerge` [1] which should, in theory be capable of doing an ordered merge of documents in a medallion config.d directory.

Would the following configuration hunting flow be sensible? Are there any other cases which should be handled?

![config-flow](https://user-images.githubusercontent.com/58414429/93841428-e7c6fc80-fcd6-11ea-97bc-3e44f2193054.png)

[0] https://github.com/hynek/environ-config
[1] https://github.com/avian2/jsonmerge

**Comment by zrush-mitre** [comment]
This flow seems pretty reasonable, though the general usage will need to be documented, as well as the specific paths for default config and directory.

**Comment by maybe-sybr** [comment]
Sure thing, I'll roll some more changes into #136 and un-draft it when that's complete. Thanks for looking this over :)

**Comment by zrush-mitre** [comment]
Branch merged. Closing this issue.
