### ISSUE TITLE
Ability to use as a library in an existing Flask application

### ISSUE THREAD

**Issue by JasonKeirstead** [oasis-open/cti-taxii-server#14]
It would be nice to be able to use Medallion as a library in an existing application. The way it is currently structured (with assumptions of "auth" throughout the code) makes this not possible.

**Comment by gtback** [comment]
Thanks, @JasonKeirstead . I'm a bit hesitant to encourage people to use this in production applications, but I can see why it would be valuable.

**Comment by brunes007** [comment]
@gtback What do you mean exactly...

Going to submit a new PR as my fork now has everything working.

**Comment by gtback** [comment]
@brunes007 : I meant this, from the README:

> WARNING: medallion was designed as a prototype and reference implementation of TAXII 2.0, and is not intended for production use.

It doesn't handle a lot of the things you'd want in a production server, though it's possible if you incorporate it into a larger Flask app that already provides those things, it might be OK.
