### ISSUE TITLE
POST requests does not write into the data.json file

### ISSUE THREAD

**Issue by scorpix06** [oasis-open/cti-taxii-server#143]
Hello,

I am building a TAXII server, for my test I use a data file (later I will use mongodb).

When I do a post request to add an object I have a return code 202 and I can find my post data with a get request to the collection.

But the data is not in my data.json file and when I restart the server I lost all my data.

Could you help me ? Maybe when I will use mongodb it will work fine ?

(Sorry for my english it's not my native langage)

**Comment by zrush-mitre** [comment]
Hi @scorpix06,

TAXII servers do not automatically save the objects ingested, as most of the time these servers are left up for very long periods of time. I did implement a `save_data_to_file()` function in the memory backend for manually saving, but there's no implementation for the Mongo backend. You could definitely implement something similar by just querying for all your objects and putting them in a JSON file, or you could port the code into the Mongo backend directly.

If requested, a Mongo function for saving to a file could get implemented here, but it would definitely be some time. 

Thanks

**Comment by rpiazza** [comment]
Please respond if you are interested in this feature, and we will reopen it
