### ISSUE TITLE
TAXII 2.1 / 2.0 in medallion 3.0

### ISSUE THREAD

**Issue by m1kl0s** [oasis-open/cti-taxii-server#148]
Hello

I can get my TAXII server to work with TAXII 2.1 clients.
But TAXII 2.0 clients cannot discover any collections whatsoever, what am I missing in my configuration or have overlooked? I would like to support both versions in my server.

Appreciate any help.

Thanks

**Comment by chisholm** [comment]
Current Medallion supports TAXII 2.1 only.

https://github.com/oasis-open/cti-taxii-server/blob/46c89eb56b681003a4399cce6214f500176e86cc/medallion/views/__init__.py#L21-L22

**Comment by m1kl0s** [comment]
> Current Medallion supports TAXII 2.1 only.
> 
> https://github.com/oasis-open/cti-taxii-server/blob/46c89eb56b681003a4399cce6214f500176e86cc/medallion/views/__init__.py#L21-L22

Aha. Understood. Unfortunately I missed that. I need to think of an alternative then, because I need to support both client versions.

**Comment by m1kl0s** [comment]
Closed.
