### ISSUE TITLE
HTTP error 400 when getting 100+ objects

### ISSUE THREAD

**Issue by m1kl0s** [oasis-open/cti-taxii-server#152]
Hello,

When querying a collection with more than 100 objects, I get returned a HTTP error 400.

requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://taxiiservername/trustgroup1/collections/64993447-4d7e-4f70-b94d-d7f33742ee63/objects/?limit=100&next=0f4f524d-9120-4483-9cde-4322b493db81

If I raise the max_page_size to 1000 it will work, since I have less than a 1000 objects.
But shouldn't the next parameter work in this case? Go for 100, then next etc.

Also, I am running this instance in a docker environment behind a loadbalancer redirecting https to http.
If I run it on ubuntu outside of docker I don't come across this error, and with this solution I do not have a loadbalancer in front.

Any ideas on why I get this error for my medallion setup in docker?

**Comment by chisholm** [comment]
Tracking paging requires some server side state to be maintained.  When you pass that "next" parameter back to the server, it looks up that UUID up to determine where it left off in the larger paging operation.  Paging state is automatically expired/dropped on a configurable timer (see check_interval/session_timeout backend settings).

Perhaps your loadbalancing involves multiple servers.  The page tracking state is not shared among them.  The memory backend is designed to not rely on any database, so there's not really any simple way to share that state.  The mongo backend uses the mongo database, but the paging state is not currently saved to it.  STIX content is there, but not any implementation details regarding paging state management.  Medallion wasn't written with a multi-server style of usage in mind.

So one idea about what has happened is that the request for the first page goes to one of the medallion instances and establishes paging state there, then the request for the next page goes to a different instance where there is no paging state.  The "next" UUID is not recognized, so you get the 400 error.

**Comment by m1kl0s** [comment]
> Tracking paging requires some server side state to be maintained. When you pass that "next" parameter back to the server, it looks up that UUID up to determine where it left off in the larger paging operation. Paging state is automatically expired/dropped on a configurable timer (see check_interval/session_timeout backend settings).
> 
> Perhaps your loadbalancing involves multiple servers. The page tracking state is not shared among them. The memory backend is designed to not rely on any database, so there's not really any simple way to share that state. The mongo backend uses the mongo database, but the paging state is not currently saved to it. STIX content is there, but not any implementation details regarding paging state management. Medallion wasn't written with a multi-server style of usage in mind.
> 
> So one idea about what has happened is that the request for the first page goes to one of the medallion instances and establishes paging state there, then the request for the next page goes to a different instance where there is no paging state. The "next" UUID is not recognized, so you get the 400 error.

Hello chisholm

Thank you very much for the elaboration, it really helped a lot. I've solved the issue by using sticky sessions in my AWS loadbalancer! I will close the issue.
