### ISSUE TITLE
Unable to run medallion

### ISSUE THREAD

**Issue by timebotdon** [oasis-open/cti-taxii-server#156]
I'm trying to run the medallion server locally from the console, however I'm being errored out with a "no module parameter provided for the TAXII server". Here's the full error message:

```
medallion --host 0.0.0.0 --port 5000 config.json      
                                        
Traceback (most recent call last):                                                             
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main                            
    return _run_code(code, main_globals, None,                                                 
  File "C:\Python39\lib\runpy.py", line 87, in _run_code                                       
    exec(code, run_globals)                                                                    
  File "C:\Python39\Scripts\medallion.exe\__main__.py", line 7, in <module>                    
  File "C:\Python39\lib\site-packages\medallion\scripts\run.py", line 80, in main              
    set_config(application_instance, "backend", configuration)                                 
  File "C:\Python39\lib\site-packages\medallion\__init__.py", line 54, in set_config           
    flask_application_instance.medallion_backend = connect_to_backend(config[prop_name])       
  File "C:\Python39\lib\site-packages\medallion\__init__.py", line 68, in connect_to_backend   
    raise ValueError("No module parameter provided for the TAXII server.")                     
ValueError: No module parameter provided for the TAXII server.                                 
```

This is my `config.json` file. I'm using the default config as stated in  the repo's readme:
```
{
    "backend": {
      "module_class": "MemoryBackend",
      "filename": "default_data.json"
    },
    "users": {
      "admin": "Password0",
      "user1": "Password1",
      "user2": "Password2"
    },
    "taxii": {
        "max_page_size": 100
    }
}
```

The error as mentioned points that its looking for a "module" key in the config, but that does'nt even exist in the documentation. What "module" should I be adding to the config?

**Comment by rpiazza** [comment]
Try a -c before the config file name on the command line

**Comment by chisholm** [comment]
If you're on 3.0.0, have a look at the config file in the medallion/test/data directory.  It includes both `module` and `module_class` properties.

https://github.com/oasis-open/cti-taxii-server/blob/v3.0.0/medallion/test/data/config.json

This seems to have been subsequently simplified, but I think those changes haven't yet been included in a release.  E.g.

https://github.com/oasis-open/cti-taxii-server/commit/82291fbb6a59d358f11fe0c169eace25d2777bac
https://github.com/oasis-open/cti-taxii-server/commit/0078812e207f46c6814ba9a64eab545d5b7b345a

So you might try changing your config structure to what 3.0.0 expects.

I looked at the readthedocs documentation:

https://medallion.readthedocs.io/en/latest/custom_backend.html#how-to-load-your-custom-backend

There, it says "A previous implementation allowed a dotted module path to be specified in the module key".  Seems like the documentation may have jumped ahead of the latest released version of medallion?  Anyway, the `module` property is mentioned there, although as being old and deprecated.  Maybe we need another medallion release?

**Comment by timebotdon** [comment]
I see now! I've been using the pip implementation of medallion which is version 3.0.0. However i was referencing the config file from the "latest" version instead - hence causing the mismatch of configs. 

Yes I thoroughly agree that should be another medallion release at least to clear up any future confusion. Thanks!
