### ISSUE TITLE
Is there a reason to why initialize_mongodb.py, reset_db() is never being called?

### ISSUE THREAD

**Issue by m0jtaba** [oasis-open/cti-taxii-server#23]
the function reset_db() is never being called, is this intended?

**Comment by rpiazza** [comment]
All code and data in the test directory is for testing purposes.  reset_db() is called in testing_mongodb_backend.py.  reset_db() will populate the mongo db with fake STIX data which is then used in the test.

**Comment by m0jtaba** [comment]
ah right! based on the documentation it mentioned that if you run the file then it work but as I found out that this wasn't the case. Maybe I misread the documention. thanks for clearing it up.
