### ISSUE TITLE
BasicFilter.process_filter() can have index error when called with empty object list

### ISSUE THREAD

**Issue by mbastian1135** [oasis-open/cti-taxii-server#29]
This came out during testing for python-stix2.TAXIICollectionSource. Looks to be a bug as process_filter() is called many times from within the taxii-server library where it is possible and appropriate that it would be called and supplied with an empty list of objects to operate on.

Index range error triggered by this line when data=[]:
https://github.com/oasis-open/cti-taxii-server/blob/6b9a1657b5f15e2a5ca185dc5a961d104f91ad61/medallion/filters/basic_filter.py#L179

**Comment by gtback** [comment]
Fixed by #38
