### ISSUE TITLE
Return 422 if object type not supported

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-taxii-server#30]
As specified [here](https://docs.google.com/document/d/1Jv9ICjUNZrOnwUXtenB1QcnBLO35RnjQcJLsa1mGSkI/pub#h.4miz6vh6cpf5), if the object type can't be processed, the **422** HTTP error code should be returned. However, currently the server returns a 500 if you try adding a single STIX object to a collection instead of adding a bundle.

**Comment by gtback** [comment]
Fixed by #38
