### ISSUE TITLE
TAXII Server to use HTTPS

### ISSUE THREAD

**Issue by Voronsky** [oasis-open/cti-taxii-server#33]
Hello !

 I have a simple question for the TAXII server. I am wondering, as I could not find it documented in the readthedocs, but if I wanted to have all TAXII communication to be done via HTTPS versus HTTP , how can I enforce that, or where do I enforce it?

An example could also be helpful if possible to be provided!

Thank you!

**Comment by gtback** [comment]
Hi, @Voronsky. Thanks for the question.

This code currently doesn't do anything with HTTPS, only HTTP. The expectation is that you would host this behind a "real" web server like NGINX which would:
- handle the TLS encryption, 
- act as a reverse proxy to the medallion server.

I agree this should be better documented. Thanks!

**Comment by Voronsky** [comment]
@gtback 

 Thank you for the response! I'll ask this one since we are still discussing SSL, but if I were to make my MongoDB require SSL with self-signed certs, would TAXII be able to work with it or would I have to edit the TAXII server's use of PyMongo to use the Certs?

 I am thinking that when a user has to write a config.json with their mongo config if it would also be possible to add a key for any keys and/or certs needed to access it to.

Thanks!

**Comment by gtback** [comment]
As you pointed out, the issue of TAXII clients connecting to the medallion server via HTTPS is completely different than connecting from medallion to the MongoDB backend. 

Right now, the only thing we support is a [MongoDB connection string](https://docs.mongodb.com/manual/reference/connection-string/). See [this line](https://github.com/oasis-open/cti-taxii-server/blob/25b75a6e165655fe5893fb0b5c529bc549c5f9b3/medallion/backends/mongodb_backend.py#L22). I would accept a PR that adds other [configuration options for `MongoClient`](https://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient), but please open another issue if you want to discuss that more. I don't want to confuse anyone about the current issue.

**Comment by Voronsky** [comment]
@gtback  Awesome, we will try that and open a new issue if need be. Thanks again!
