### ISSUE TITLE
BUG: filtering collection objects doesn't actually work for "added_after"

### ISSUE THREAD

**Issue by johntmyers** [oasis-open/cti-taxii-server#40]
In `basic_filter.py` ...

Current code has:

```python
        match_version = self.filter_args.get("match[version]")
        if "version" in allowed:
            if not match_version:
                match_version = "last"
            if len(data) > 0 and self.is_manifest_entry(data[0]):  # NEED TO CHECK EMPTY RESULTS!
                results = self.filter_manifest_entries_by_version(results, match_version)  # THIS IS BAD
            else:
                new_results = []
                for bucket in BasicFilter._equivalence_partition_by_id(results):
                    new_results.extend(self.filter_by_version(bucket, match_version))
                results = new_results
        added_after_date = self.filter_args.get("added_after")
```

First, you need to make sure you're data array actually has data in it, then you need to filter on the actual `manifest_info` array.

**Comment by johntmyers** [comment]
Ok, so it appears you assume all objects in `results` have a `modified` key, for whatever reason, when testing with STAXX, they sometimes will add objects that do not have, such as a marking-definition.

So my `results` array had this:

```json
{"created": "2018-08-18T08:38:43.559327Z", "definition": {"tlp": "green"}, "definition_type": "tlp", "id": "marking-definition--2496e5bf-137a-5dfa-bf89-8c47bc4bc277", "type": "marking-definition"}
```

The other objects in the collection reference this marking-definition. Bottom line, not all objects have a `modified` field, so this is a bad check to make to "assume" the list you are processing are manifest entries.

**Comment by clenk** [comment]
Thanks for filing an issue, @johntmyers! We'll take a look at this when we get a chance.

**Comment by rpiazza** [comment]
@johntmyers,

We just had a fix for a similar problem for the mongodb filter.  If you are interested in creating a pull request asap - you can look in mongodb_filter.py for some hints.  Otherwise, we will get to this as soon as we can.
