### ISSUE TITLE
BUG: checking new object IDs as existing already always fail

### ISSUE THREAD

**Issue by johntmyers** [oasis-open/cti-taxii-server#41]
https://github.com/oasis-open/cti-taxii-server/blob/f6398926d866989201e754dca0fec1e1a041acdf/medallion/backends/memory_backend.py#L166

This line will always fail, you're checking that the ID of the object belongs in the array of objects instead of checking if the ID of the object exists as the ID of _any_ of the objects

**Comment by clenk** [comment]
Thanks for finding this bug! We'll get to this when we get a chance, but we'll welcome a PR if you have the time.
