### ISSUE TITLE
url

### ISSUE THREAD

**Issue by mychoa2** [oasis-open/cti-taxii-server#5]
Can I get the url after running the taxii server? the url is for discovery and get the service provided in the server. Thanks

**Comment by rpiazza** [comment]
I'm not exactly sure what you are asking for.    When you send a discovery request to a taxii server - it sends back information about URLs that can be used to access api_roots.  Those roots might or might not be on the same server that you send the discovery request to.

**Comment by gtback** [comment]
@mychoa2 By default the server runs on http://127.0.0.1:5000/ . This is shown in the output of run.py.

To access the Discovery Endpoint, access http://127.0.0.1:5000/taxii/ .

Does that help, or were you looking for something else?

**Comment by emmanvg** [comment]
@mychoa2 were you able to solve the problem? Otherwise, I will close this issue as it seems more of a clarification rather than a code issue.

**Comment by gtback** [comment]
If you still have questions, feel free to re-open this, @mychoa2
