### ISSUE TITLE
MissingPropertiesError: No values for required properties for Relationship: (relationship_type, source_ref, target_ref).

### ISSUE THREAD

**Issue by lorinwu** [oasis-open/cti-taxii-server#51]
hello, 

I wanted to push a relationship object to taxii server with below:

```python
from stix2 import TAXIICollectionSink, ThreatActor

#create TAXIICollectionSINK and push STIX content to it
tc_sink = TAXIICollectionSink(collection)

# tc_sink.add(bundle)
tc_sink.add(identity)
tc_sink.add(indicator)
tc_sink.add(relationship)

relationship = Relationship(relationship_type='indicates',
                            source_ref=indicator.id,
                            target_ref=malware.id)

tc_sink.add(relationship)
```

then, I tried to pull them to apply to our application, but an error occured:

```python
# supply the TAXII2 collection to TAXIICollection
tc_source = TAXIICollectionSource(collection)

#retrieve STIX objects by id
stix_obj = tc_source.get("relationship--3d899276-f4bd-445d-a4d8-9122161a6dcc")
```

but when I trying to retrieve them, the return object lost the relationship_type, source_ref, target_ref, however I checked mongo db, all properties stored, could you know how to address it?

**Comment by lorinwu** [comment]
appending more.
should I know some properties will be ignored by default? when I push an identity object to taxii server, the property "description" disappeared, mongo db also does exist. Thanks.

**Comment by lorinwu** [comment]
solved, just need to modify/add/change mongo db filter project content. But how I wonder if possible to change them by some configuration or added directly on TAXII-Client?

**Comment by emmanvg** [comment]
related to #47

**Comment by emmanvg** [comment]
@lorinwu thanks for this report. I can confirm there is a bug with the MongoDB backend filtering that will strip out some properties from the . Internally the object is ok.

**Comment by lorinwu** [comment]
thank you @emmanvg, the workaround we did: add necessary properties of SDO we now are using to the MongoDB backend. Hope we can load the filtering content from some configuation file or pull them  just by adding some arguments, then we can do it better in the future :)
