### ISSUE TITLE
Python throws KeyError: 'taxii' error when starting medallion

### ISSUE THREAD

**Issue by jtcotton63** [oasis-open/cti-taxii-server#57]
Hey all,

I'm trying to spin up a test TAXII server for a project. I found this implementation and decided to give it a go instead of rolling my own.

**The problem**

When I run `medallion config.json`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/medallion", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/medallion/scripts/run.py", line 78, in main
    set_config(application_instance, "taxii", configuration)
  File "/usr/lib/python3.6/site-packages/medallion/__init__.py", line 39, in set_config
    flask_application_instance.taxii_config = config[prop_name]
KeyError: 'taxii'
```

**Setup steps performed**

I followed the instructions in the Installation and Usage sections to set up medallion:

- I installed python3.6 and pip3.6
- I ran `sudo pip3.6 install medallion`
- I created my config file based on the Usage instructions (see below)
- I ran `medallion config.json`, which produced the error reported above.

Config file:

```
{
     "backend": {
        "module": "medallion.backends.mongodb_backend",
        "module_class": "MongoBackend",
        "uri": "mongodb://localhost:27017/"
     },
    "users": {
       "admin": "Password0",
       "user1": "Password1",
       "user2": "Password2"
    }
}
```

**Notes**

- OS: Centos 7.6
- Python version: 3.6.8
- medallion version: 0.4.0

Any ideas how to get around this?

Thanks in advance!

**Comment by clenk** [comment]
Hi @jtcotton63, thanks for the detailed bug report. The code is expecting a `taxii` section in the config, like you can see in the [sample config file](https://github.com/oasis-open/cti-taxii-server/blob/master/medallion/test/data/config.json). We need to fix it to work when with some defaults when some config values aren't present, but in the meantime you can try adding the following to your config file:

```json
"taxii": {
      "max_page_size": 100
}
```

**Comment by jtcotton63** [comment]
That fixed it! Thanks for the prompt response @clenk!
