### ISSUE TITLE
memory_backend.py add_objects() expecting objs to be a dict; it appears to be passed as a string.

### ISSUE THREAD

**Issue by cricard** [oasis-open/cti-taxii-server#6]
It appears that the add_objects() function in memory_backend.py is expecting objs to be a dictionary.  It appears to be being passed as a string.

At some point, I believe the json string needs to be converted to a dict.  One possibility would be to convert it to a dict in add_objects(); something simple like adding the following seems to work: 

objs=json.loads(objs)

**Comment by rpiazza** [comment]
I have tested this, using the cti-taxii-client and a dictionary was passed into memory_backend.add_objects (see screenshot )
<img width="1384" alt="screen shot 2017-11-01 at 1 55 28 pm" src="https://user-images.githubusercontent.com/2091129/32289192-6d591cd6-bf0c-11e7-8b2e-92101f3473b9.png">
Can you give us more context??

**Comment by cricard** [comment]
OK - I think I see what's going on.  It looks like taxii2client's add_objects() expects the STIX bundle to be a python object, not a json-formatted string.  I was passing a json-formatted string. If I deserialize the json string before passing it to add_objects(), it works fine as-is.

Would it make sense for taxii2client's add_objects() to either throw an error or attempt to deserialize it if it's passed a string?

**Comment by rpiazza** [comment]
That seems reasonable.

**Comment by emmanvg** [comment]
@gtback @rpiazza, is this still relevant based on the recent changes we made to `taxii2client`?

**Comment by rpiazza** [comment]
It now accepts a string?

**Comment by emmanvg** [comment]
Yeah, now you have to provide a json-formatted string of a Bundle to `taxii2client.add_objects()`. So you can perform any of the ones below:
``` Python
taxii2client.add_objects('{"type": "bundle", "objects": [{"description": "Real bad malware", "created": "2018-03-21T19:13:24.532Z", "labels": ["ransomware"], "modified": "2018-03-21T19:13:24.532Z", "type": "malware", "id": "malware--b86e313e-fdc3-4f7e-b9b3-aee9e4f0bac3", "name": "Test"}], "spec_version": "2.0", "id": "bundle--5fb13b50-8566-42e8-b2a4-85f728473366"}')

# OR

taxii2client.add_object(Bundle(malware_obj).serialize())
```

**Comment by rpiazza** [comment]
@cricard:  see if this works for you

**Comment by gtback** [comment]
I don't think this is an issue any more on the client side. I think it's also the solution @treyka was trying to make in #12. 

In any case, we should be careful to distinguish between JSON (strings) and python dictionaries (not strings); I know I will often use "JSON object" or just "JSON" to mean a Python dictionary, which is wrong.

It also doesn't help that both the taxii2client and the taxii2server's backends both have an add_objects() function, which don't accept the same things.
