### ISSUE TITLE
memory_backend.py update_manifest() is expecting all new_obj STIX objects to have a "modified" element.  Not all STIX 2.0 objects do.

### ISSUE THREAD

**Issue by cricard** [oasis-open/cti-taxii-server#7]
It appears that update_manifest() requires all STIX objects to have a "modified" element, that it uses  to update the STIX object's version history.  If there is not a modified element present, it throws an error.

However, not all STIX 2.0 objects have a "modified" element.  For example, a Marking-Definition STIX 2.0 object cannot have a "modified" element.  If your STIX bundle contains a Marking-Definition object, update_manifest() will throw an error.

**Comment by gtback** [comment]
Thanks, @cricard . I feel like we ran into a similar issue lately, but I can't find it. I agree this needs to be fixed.

**Comment by rpiazza** [comment]
I asked a question on the TAXII slack channel on ideas on how to implement this.  Of course, no one answered the original question.

**Comment by packet-rat** [comment]
Try the public list vs. non-public Slack Channels?

**Comment by rpiazza** [comment]
Because "versions" is an optional property, the fix will be just to not populate that property when the "modified" property is not present.

**Comment by rpiazza** [comment]
After discussion on slack, it was decided to include the "created" timestamp for the one and only version of a Marking-Definition manifest entry
