### ISSUE TITLE
Improve Mongo backend query efficiency

### ISSUE THREAD

**Issue by chisholm** [oasis-open/cti-taxii-server#89]
The current backend stores manifests and objects separately (they are separate collections).  Several types of queries require "joining" those two collections together, to match each object to its corresponding manifest.  The way this is done is complicated and quite inefficient, owing to the fact that Mongo's "$lookup" pipeline step can only join on one property, and matching an object to its manifest requires checking both ID and version.  An additional complication is that an object's version isn't in a fixed property, e.g. it may come from either the "created" or "modified" properties.

Since manifests and objects map 1:1 in TAXII 2.1, one suggestion is to store an object and its manifest within the same Mongo document.  That way, no join is required to match them up.

**Comment by emmanvg** [comment]
closed by #117
