### ISSUE TITLE
Return empty envelope in certain cases

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-taxii-server#98]
Specifically on the https://github.com/oasis-open/cti-taxii-server/tree/taxii2.1-csd03 branch, in the memory backend, there are a couple cases where endpoints return 404 but should instead return an empty envelope:

- [x] the get-objects endpoint, if a collection is empty and no filters are provided
- [x] the get-manifests endpoint, if a collection is empty or if filters filtered everything out

Thanks to @chisholm for finding this.

**Comment by emmanvg** [comment]
Available in v2.0.0
